### ISSUE TITLE
I need to include one specific JS file into the iorad web service which does main capturing 

### ISSUE THREAD

**Issue by sargsyantaron** [iorad/integrations#10]
Here is the story.

The iorad.js opens iframe when i use it, i want to have the same functionality  int the main page where capturing starts. means when I call create new tutorial function im getting redirected(within iframe) to //www.iorad.com/server/?a=app.editor&amp;data=0&amp;src=iframe from there once finish button is pressed I'm getting back into event handler and I'm able to get turtorialPArams which i need. What I need right now is to have the same functionality inside that page + in that page I want to have js file included which does my work.

Please contact me if you will have ay questions. I'm mostly online.

Thanks
Taron

**Comment by hoatle** [comment]
seems that your request with iorad.js is impossible. I still have no idea how to do that, I could possibly need to ask backend guys to see if this is possible.

**Comment by iorad** [comment]
@sargsyantaron can you provide a specific example of what you are looking to do with code.

**Comment by sargsyantaron** [comment]
basically what can work out is: i want //www.iorad.com/server/a=app.editor&data=0&src=iframe&plugin_type=confluence_cloud&return_url=mydomain.com

the link above is the link where capturing starts, what I want is at the end when user press finish button i want to be redirected to  return_url with all tutorial related parameters, for example in our case it will be 

mydomain.com?uid=123123&tutorialId=324234&tutorialTitle=sometitle. I only need this for plugin_type=confluence_cloud.

**Comment by hoatle** [comment]
I'm not sure if this could expose any security risk and this should be done on the backend (cc @yasir and @binamra)

**Comment by sargsyantaron** [comment]
in regular case iframe sends message which is being handled by iorad.js, in this case we cant archive that, another way is to do all in backend side. just let me know how you want to proceed.

thanks

**Comment by iorad** [comment]
@Binamra or @yasirrose please reply

**Comment by binamra** [comment]
@sargsyantron it looks doable to me. Basically you want to redirect to an url after finishing the capture  and you want all tutorial parameters to be passed as query string. This can be accomplished from the server side script. We can have a discussion tomorrow night and implement it. Somewhere around 10PM IST. I am travelling at the moment. Let me know your IM details.

**Comment by sargsyantaron** [comment]
@binamra That was one scenario we can go, the weak side of that scenario is that you will also need to include confluence related js files and exclude them on other cases, anyway both ways is ok for me.

Please call me via VIBER +37477365066

Thanks
Taron

**Comment by binamra** [comment]
@sargsyantaron  do you have a skype account. That ll be feasible for me. Let me know.

**Comment by sargsyantaron** [comment]
skype : snooze-g

**Comment by sargsyantaron** [comment]
i'm also available through slack

**Comment by iorad** [comment]
@sargsyantaron how many js files there you need to include.  Can you add it somewhere in the integration repo...so @yasirrose can take a look at this.

**Comment by binamra** [comment]
@sargsyantron I pinged you bit late yesterday. I ll positively have a discussion with you and address this issue today.

**Comment by binamra** [comment]
@sargsyantaron as per our previous discussion we are supposed to talk tonight again to finalize things. Let me know your feasible time. I will make myself available.

**Comment by binamra** [comment]
@sargsyantaron thanks for the call. @Maluen after the user clicks finish when capture completes @sargsyantaron wants a redirect to some domain based on the plugin type. The redirection will be done passing w some query string parameters containing tutorial metadata. As the finish button of capture  is in JS.  @hoatle sense some security risk while doing other domain redirection from   JS. From backend point of view we can do the redirection checking any url parameter. But for that JS need to pass something in url (a token or an encrypted string).  Then the backend will check for it and do the redirection.  

@Maluen need your input on this.  @sargsyantaron need this done to proceed further.

**Comment by Maluen** [comment]
@binamra Is the redirect always restricted  to the same domain (e.g. freshdesk.com for freshdesk plugin) or can be to any url?
In the first case, server can ensure that the url matches the "plugin domain".

Right now, when user clicks "Finish" on the editor, an HTML5 message is sent to the parent frame (the one that contains the embedded editor), where the iorad.js API is running.

Thus the redirect probably needs to be executed by the iorad api itself (eventually by using some additional parameter sent by the embedded editor).

**Comment by iorad** [comment]
@Maluen this new requirement is only for plugin type confluence-cloud ... For all others this should stay same including plugin type confluence

**Comment by Maluen** [comment]
Probably this should be handled by @hoatle or other iorad api developer, I can make changes to editor as required.

**Comment by binamra** [comment]
@Maluen @hoatle can we discuss on slack about this today. Infact @sargsyantaron is waiting on this. So will be better to address this asap. Let me know.

**Comment by Maluen** [comment]
https://github.com/iorad/iorad/issues/2459#issuecomment-147359949

>
Hi,
>
regarding running capturer from iframe inside iframe
>
it wont work under chrome, mac osx, but it works for firefox
I have used tes-api and my code as well, in both cases it is not running capturer
>
thanks
taron

Works for me on localhost:9000 with grunt server, Chrome + Windows and http://localhost:9000/api-test/parent.html

Didn't worked before applying the fix.

@hoatle can you please check if it works for you on Windows and Mac?

**Comment by hoatle** [comment]
@Maluen it works on my Mac:
- iorad capture: 0.9.26
- OX X El Capitan (10.11)
- Chrome: 45.0.2454.101 (64-bit)
- Firefox: 41.0.1
- Safari: 9.0 (11601.1.56)

I checked on parent.html, with each check, I quit iorad capture and the capture works as expected.

**Comment by Maluen** [comment]
@sargsyantaron please clear your cache and retry, or if the problem still happen, provide detailed information and exact steps for how to reproduce the problem.

**Comment by binamra** [comment]
@sargsyantaron should we close this issue.
