### ISSUE TITLE
I need some place on iorad.com to host confluance cloud plugin

### ISSUE THREAD

**Issue by sargsyantaron** [iorad/integrations#11]
Hi

I need access to iorad.com to put my files into conf_cloud folder in the way that fils can be accessed via 

iorad.com/conf_cloud 

I need ftp or other file protocol access like sftp.

Thanks
Taron

**Comment by iorad** [comment]
@phuonglm can you look at this?

**Comment by phuonglm** [comment]
@sargsyantaron do you mean this folder on github? https://github.com/iorad/integrations/tree/master/atlassian_integration/conf-cloud-plugin 
if that folder so it already avaible at http://www.iorad.com/server/assets/bower_components/integrations/atlassian_integration/conf-cloud-plugin

To update that directory you will need to push change to master branch of this repository.

**Comment by phuonglm** [comment]
I you still need the path http://iorad.com/conf_cloud i'll map that path (or what every directory in this repository) to that directory above. All you need is push it to this repository branch master.

**Comment by sargsyantaron** [comment]
cool thanks

**Comment by sargsyantaron** [comment]
you know just dont do anything 
I think the url is ok)
dont waist your time 

thanks
