### ISSUE TITLE
I need some help with oauth 1.0a

### ISSUE THREAD

**Issue by dan753722** [iorad/integrations#14]
I have implemented integration on Uservoice's knowledge base home page.

It's implemented purely with JavaScript.

OAuth is required for uservoice APIs.

I am using this library to achieve http header authentication: [oauth1.0a](https://github.com/ddo/oauth-1.0a)

After the complicated 3 legged authorization, I could use the ```topics.json GET``` endpoint fine.

However, I can't do a ```article.json POST``` call.

error is : not authenticated.

uservoice support has not been helpful. Apparently, since we are using their trial account, we can't escalate the issue to their technical team for further assistance without paying some $$$$.

I'd like to have another set of eyes to review my prototype code and hopefully may have some ideas on what went wrong...

@iorad please assist :)

**Comment by hoatle** [comment]
@dan753722 let's discuss.

**Comment by hoatle** [comment]
@dan753722 I found the problem:

please see the change below fill fix the problem (don't set `oauthData.oauth_verifier = oauthVerifier;`) and it should work.

```
    module.getOauthHeader = function (ajaxOptions) {
        debugger;
        var oauthData = oauthClient.authorize(ajaxOptions, { public: oauthToken, secret: oauthTokenSecret });
        //oauthData.oauth_verifier = oauthVerifier;
        return oauthClient.toHeader(oauthData);
    };
```

**Comment by dan753722** [comment]
@hoatle you are a champ! I will give it a go :)
