### ISSUE TITLE
Finish event case needs to be handled by confluence add on and freshdesk/zendesk app

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#19]
You can reproduce with the link https://teracy1.freshdesk.com/solution/articles/9000010729-testing-iorad-on-freshdesk, log in with the account: rocksunflower122@gmail.com/123456
- Edit a tutorial
- Click Finish

Actual outcome: The Finish button is not working
![finishonfreshdesk](https://cloud.githubusercontent.com/assets/1079960/11838197/fd5acb0c-a417-11e5-9a60-94694b0abb7e.png)

**Comment by iorad** [comment]
@sargsyantaron @dan753722 we need the event handled when user edits a tutorial using the edit button in the tutorial....

You can find more details here https://github.com/iorad/iorad/issues/2733#issuecomment-166298811

**Comment by sargsyantaron** [comment]
from conf/jira plugin side the only thing matters is tutorial id, uid
i get them via editor closed event, so it should be ok without any changes .

have you fund any bug in conf/jira or this is assumption?

**Comment by iorad** [comment]
Actually this case doesnt work in any plugin

(1) Open confluence page
(2) Insert colution
(3) Capture
(4) Save/preview
(5) Click edit button (in player)
<img width="291" alt="edit" src="https://cloud.githubusercontent.com/assets/5091446/11936654/440fcb4c-a7dd-11e5-8723-df5135688762.PNG">
(6) Make change
(7) Click Finish 

Nothing happens this case happens in all plugin (freshdesk, zendesk and confluence) 

Maybe there is a generic way to handle this and make finish button return to original view or reload page?

**Comment by sargsyantaron** [comment]
this is iorad functionality right ? 
not any integration one am i right ? if so we need to fix this on iorad.js  side?

**Comment by iorad** [comment]
@hoatle would be better equipped to answer this.  @hoatle is there anyway we can fix the api to basically just forward to the original url....this would be a better solution iof we can accomplish this?

**Comment by hoatle** [comment]
iorad.js just provides as a library, not handling the event behavior. In this case, 'editor:close' event is trigger and the plugin code (integration plugins) should handle that event, for example: when 'editor:close' is triggered, the plugin code should listen to it and should display the tutorial in play mode instead of edit mode (like the way a new tutorial is created and then "finish" button is clicked).

Note: `editor:ready` event is triggered and the configuration plugins should listen to it and register the events.

**Comment by sargsyantaron** [comment]
iorad.on('editor:close', ... 
is always handled on mi side, @iorad can you please give me cloud account details I will check it tomorrow.
there seems to be something else.

**Comment by iorad** [comment]
its not a special case it happens in every occurance.  It just needs to be handled

https://ioradsun.atlassian.net/wiki
ioradsun@iorad.com
pippen33

create a tutorial
save it
check it out in preview mode
Edit the tutorial (using the edit button in the player)
Make edit
and click finish (it should revert to player again) right now we have to refresh to see changes

**Comment by dan753722** [comment]
from zendesk help center and freshdesk point of view, they both restrict modification on their article editor.

The only way I can think of to tackle this is to add a invisible widget on freshdesk portal and help center article page, assuming the owner of a tutorial goes to the public article page on the portal to edit it? User experience is very poor this way.

**Comment by hoatle** [comment]
I'm not sure if we need to continue working on this. Assigned to @iorad to confirm first.
