### ISSUE TITLE
[Firefox] Bug: Cannot select Solution in the Iorad Screen Capture popup

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#20]
You can reproduce with the link https://teracy12.freshdesk.com/helpdesk/tickets/2
Username: hoavt122@gmail.com
Password: amisun85

Log in Freshdesk
Click Create knowledgebase solution button
Select a category from the drop-down list in the Iorad Screen Capture popup
Actual outcome: when the category is selected, the Solution is not changed
Expected outcome: when the category is selected, user should be able to select any Solution folder of the category.

**Comment by dan753722** [comment]
I followed these steps however, I couldn't seem to reproduce your issue. solution dropdown list seems updated properly to me.
