### ISSUE TITLE
Bug: The Iorad Screen Capture on Freshdesk is reloaded

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#21]
You can reproduce with the link https://teracy1.freshdesk.com/helpdesk/tickets/1
username: hoavt@teracy.com
password: amisun85
- Log in Freskdesk
- Click Create Knowledgebase solution --> The Iorad Screen Capture is shown
- Click Capture Solution --> user is redirected to the Log In page
- Navigate  to other pages, for example, Log In, Sign Up, Pricing...

Actual outcome: 
- On Chrome: 
  The Iorad Screen Capture (as the screenshot below) on Freshdesk is reloaded in a second.
  ![ioradscreencapture](https://cloud.githubusercontent.com/assets/1079960/11918035/2e917002-a753-11e5-80a7-9664139646a4.png)
- On IE11: The iorad logo moves from the left to the center on Freshdesk, Zendesk and Atlanssian.

**Comment by dan753722** [comment]
@iorad I can't reproduce this one either.
