### ISSUE TITLE
iorad integrations completely broken - URGENT

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#22]
@phuonglm @dan753722 @sargsyantaron our integrations are completely broken when clicking capture

the url is going to https://www.iorad.com/server/?a=app.editor&data=0&src=iframe&referrer=https://ioradsun.zendesk.com/agent/apps/iorad&plugin_type=zendeskapp_solutions&origin=https%3A%2F%2Fioradsun.zendesk.com&app_guid=6b4794b2-41ed-4d89-8d3c-587ee9af2c03

**Comment by iorad** [comment]
as per @phuonglm the problem for this
editor.js:1643 Uncaught ReferenceError: siteWindow is not defined(…)(anonymous function) @ editor.js:1643

is around this line https://github.com/iorad/iorad/blob/d4d302166ed802b80e9cff8bc79bb9543781820e/app/scripts/base/config.js#L4

**Comment by dan753722** [comment]
as per discussion, iorad.js is not updated when we removed node from url.

**Comment by dan753722** [comment]
see commit 70c2018a7d718b501c941e1dfb94deb9f734a35a for fix
