### ISSUE TITLE
Frshdesk app popup doesnt open after capture

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#25]
@habibillah after capture in all 3 scenarios the popup doesnt open
you can check 
for all 3 options there is no popup

[9:51 PM]  
I tried https://sunfresh.freshdesk.com/helpdesk/tickets/1

[9:51 PM]  
sunfresh@iorad.com

[9:51 PM]  
pippen33

**Comment by habibillah** [comment]
Fixed
