### ISSUE TITLE
Urgent issue with confluence add on

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#31]
Go here https://ioradcon.atlassian.net/wiki/pages/editpage.action?pageId=35038
Login ioradcon@iorad.com
pippen33

When we click "Add" and "Insert Solution"

We are presented with NGIX error...looks like one of the URLS is not being forwarded

Here is a video of the problem http://somup.com/cbe1bk9uI

**Comment by phuonglm** [comment]
Seem we fixed this issue before. Need @iorad confirm.

**Comment by phuonglm** [comment]
fixed confirm, done
