### ISSUE TITLE
Nginx server showing error logs to GET IoradWebWidget.min.js (not found)

### ISSUE THREAD

**Issue by davidfaj** [iorad/integrations#35]
Nginx server is showing many error logs to GET IoradWebWidget.min.js (not found). In the last 200 errors, 138 had this issue. 2 samples below:

```2018/06/15 09:04:27 [error] 9142#0: *125452 open() "/var/www/www.iorad.com/node/static/assets/bower_components/integrations/IoradWebWidget/dist/IoradWebWidget.min.js" failed (2: No such file or directory), client: 172.99.36.194, server: iorad.com, request: "GET /freshdesk.js HTTP/1.1", host: "www.iorad.com", referrer: "https://mintek.freshdesk.com/support/login"```

```2018/06/15 09:18:32 [error] 9142#0: *126417 open() "/var/www/www.iorad.com/node/static/assets/bower_components/integrations/IoradWebWidget/dist/IoradWebWidget.min.js" failed (2: No such file or directory), client: 73.34.239.201, server: iorad.com, request: "GET /freshdesk.js HTTP/1.1", host: "www.iorad.com", referrer: "https://care.synchr.com/support/solutions/articles/24000026190--tax-update-06-14-2018/preview"```

**Comment by iorad** [comment]
@habibillah can you look at this?

**Comment by iorad** [comment]
looks like we moved this on our side...maybe we should setup a redirect @phuonglm

**Comment by iorad** [comment]
Probably best to reinstall just to have it so we dont get errors

**Comment by habibillah** [comment]
@hoatle it's ok to add IoradWebWidget into bower build?

**Comment by habibillah** [comment]
@iorad the missing file already on test now 
https://test.iorad.com/assets/bower_components/integrations/IoradWebWidget/dist/IoradWebWidget.js
https://test.iorad.com/assets/bower_components/integrations/IoradWebWidget/dist/IoradWebWidget.min.js

**Comment by iorad** [comment]
https://www.iorad.com/assets/bower_components/integrations/IoradWebWidget/dist/IoradWebWidget.min.js

https://www.iorad.com/assets/bower_components/integrations/IoradWebWidget/dist/IoradWebWidget.js

Shows up in production as well...should eliminate the errors now.

**Comment by davidfaj** [comment]
Confirmed. It's not showing in the error.log anymore, and also, it's already showing successfully in the access.log:
`114.125.119.195 - - [17/Jun/2018:22:55:22 -0400] "GET /assets/bower_components/integrations/IoradWebWidget/dist/IoradWebWidget.min.js HTTP/1.1" 200 22395 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"`
