### ISSUE TITLE
Zendesk Sell Integrrration

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#39]
@habibillah 

We need an integration with zendesk sell.  We will be listing an app in their marketplace.
Here is a video of the idea
It will work the same way as our old app in the support ticket...where we click iorad icon and capture some stuff and then it puts a link in the rich text editor
https://youtu.be/eCAMT8E4YQA

Its in the contacts area...I sent you an invite to the below sell site.

https://app.futuresimple.com/crm/contacts/266636281

we want the integration in the "Send by email" rich text editor
![email](https://user-images.githubusercontent.com/5091446/77589345-e05a9e00-6ec1-11ea-8124-ee080ad92a38.png)

**Comment by iorad** [comment]
Probably a cool idea would be to add a checkbox in the dialog.. "Add Article to guide" ...as well..so it will post it there as well.

**Comment by iorad** [comment]
If guide is connected as well.

**Comment by habibillah** [comment]
I have expoloring and implementing for zendesk sell. Unfortunately, there is lot off limitations compared to support API, and not possible to complete simple app to meet your requirements.

1. `modal location` there is no destroy api to close the modal in sell api as same zendesk support
2. no api to write to note or email, but able to capure added note. Trying any heck, but has not succeeded

as reference for sell api doc https://developer.zendesk.com/apps/docs/apps-sell-api/introduction

So what we con do for now?
-------

1. put iorad app in sidebar https://sc.kalicode.com/bf286.png
2. capture iorad tutorial in modal popup https://sc.kalicode.com/f51a9.png, but unable to close the modal
3. can get the tutorial link, but can't put it in note/email content

All we have done in zendesk support app really come from and supported by their API, but they provide fewer API for zendesk sell

what I suggest?
-------

Add the icon button by injecting to code through chrome plugin as same as confluence have.
