### ISSUE TITLE
Bug: Watch It - Video Integration Mouse Pointer Always Present

### ISSUE THREAD

**Issue by berpe** [iorad/integrations#45]
In "Watch It - Video" mode there is always a mouse pointer in the middle of the screen while watching the video. It is quite disturbing, mostly when not user mouse interaction is required.

Video to reproduce the bug here: https://www.iorad.com/player/56670/sample-tutorial#watchsteps-5

Would be a good idea to give the option to hide the pointer or just hide it by default, at least until user interaction is needed.

**Comment by iorad** [comment]
This repository is for integration related issues (ie zendesk, freshdesk, hubspot etc).  We have already noted this issue on our side.    So i'm closing it here.
