### ISSUE TITLE
Added Plugin_Type to iorad.js

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#5]
hi guys @hoatle added "plugin_type" to the iorad js api.  So when you guys get a chance make sure we add it to freshdesk, zendesk, confluence, jira, wordpress plugins.

@dan753722 @sargsyantaron

**Comment by hoatle** [comment]
the wordpress plugin registered with `wordpress`: https://github.com/iorad/iorad-editor-wp-plugin/commit/c91bba4172db628c1fdbf9b020f58a5ebd2c1a62
