### ISSUE TITLE
freshplug: need an icon for insert iorad button

### ISSUE THREAD

**Issue by dan753722** [iorad/integrations#7]
![capture](https://cloud.githubusercontent.com/assets/5967762/9495918/2ec07ad0-4c51-11e5-9d77-a5780876df4b.PNG)

In the Replay ticket editor view, at the right top corner, we want to have an iorad button. When clicked, agent can capture a tutorial and have the player iframe automatically populated in the ticket reply form.

requirement:
*dimension: 27px by 27 px
*have it hosted at iorad.com/server/assets/img

**Comment by iorad** [comment]
@dianablandon can you do this first thing when u start...

**Comment by dianablandon** [comment]
Here is the icon
![icon_iorad](https://cloud.githubusercontent.com/assets/10599150/9499087/d7814588-4be2-11e5-9627-a5a5162bd587.png)

**Comment by dianablandon** [comment]
The icon is under  iorad/server-iorad/ioradcom/assets/img/icon_iorad_freshdesk.png

**Comment by dan753722** [comment]
@dianablandon thank you so much for the effort :)
