### ISSUE TITLE
chec

### ISSUE THREAD

**Issue by iorad** [iorad/integrations#9]
## Heading ## A frustrated user opens a ticket.  You customer agent knows the solution.  What's the best way to show the user without wasting your agent's valuable time copy/pasting screenshots?

**How iorad for zendesk works - Instant step-by-step solution articles.**
Fire open the iorad for zendesk app and just click through the solution steps behind the capture frame.  That's it.  iorad does the rest.  It magically breaks the captured events and screenshots into steps, highlights where the action took place, and creates directions based on what the agent did. Click finish and it’s instantly attached to your ticket and simultaneously posted to your help center. No uploading. No screenshots. No Mess.

**Comment by dan753722** [comment]
@iorad is this an issue? can I close it?
